routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ArticuloController;
use App\Http\Controllers\VentaController;

use App\Models\Venta;
use App\Models\User;
use App\Models\Articulo;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/pdf1/{id}', function ($id) {       
    $venta= Venta::find($id);    
    $detalles=$venta->articulos;
    
    $pdf = PDF::loadView('venta.pdf1',compact('venta','detalles'));
    return $pdf->stream('invoice.pdf');
    
})->name('pdf1');


Route::get('/', function () {
    return view('layouts.admin');
});

Route::resource('articulo',ArticuloController::Class);
Route::resource('venta',VentaController::Class);

app/Models/Articulo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
//use App\Models\Venta;

class Articulo extends Model
{
    use HasFactory;
    protected $fillable=['nombre','color','descripcion','precio','stock'];

    //relacion de muchos a muchos
    //entre ARTICULO tiene muchas ventas
    public function ventas()
    {
        return $this->belongsToMany(Venta::class)->withPivot('costo', 'cantidad', 'total');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/Venta.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Venta extends Model
{
    use HasFactory;
    protected $fillable=['user_id','monto_total'];


    public function articulos(){
        return $this->belongsToMany(Articulo::class)->withPivot('costo', 'cantidad', 'total');
    }
    
}

app/Http/Controllers/ArticuloController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Articulo;

class ArticuloController extends Controller
{
    
    public function index()
    {
        $articulos=Articulo::all();
        return view('articulo.index',compact('articulos'));
    }

    
    public function create()
    {
        return view('articulo.create');
    }

    public function store(Request $request)
    {
        //return $request->all()
        Articulo::create($request->all());
        //return Redirect::action('Articulo@index');        
        return redirect()->route('articulo.index');
    }

    
    public function show($id)
    {
        //
    }

    
    public function edit($id)
    {
        $articulo=Articulo::find($id);
        return view('articulo.edit',compact('articulo'));
    }
    
    public function update(Request $request, $id)
    {
        Articulo::find($id)->update($request->all());
        return redirect()->route('articulo.index');        
    }


    public function destroy($id)
    {
        Articulo::find($id)->delete();
        return redirect()->route('articulo.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/VentaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Arr;

use Illuminate\Http\Request;
use App\Models\Venta;
use App\Models\User;
use App\Models\Articulo;

class VentaController extends Controller
{
    public function index()
    {
        $ventas=Venta::join('users', 'ventas.user_id', '=', 'users.id')
        ->select('ventas.id','ventas.monto_total','users.name')
        ->get();

        return view('venta.index',compact('ventas'));
    }

    public function create()
    {
        $usuarios=User::pluck('name', 'id'); // select * from ventas  
        //$articulos=Articulo::pluck( 'id','nombre');
        $articulos=Articulo::all();                
        return view('venta.create',compact('usuarios','articulos'));
    }

    public function store(Request $request)
    {        
        $collection=collect($request->all());
        //$keyed = $collection->keyBy('id')->get('');
        
        
        $vent=new Venta();        
        $vent->user_id=5;
        $vent->monto_total=$collection->sum('total');         
        $vent->save(); 
        
        foreach($collection as $dato){
        
            $vent->articulos()->attach($dato['id'],
                            [
                                'cantidad'=>$dato['cantidad'],
                                'costo'=>$dato['costo'],
                                'total'=>$dato['total']
                            ]);                

            $art=Articulo::find($dato['id']);
            $art->stock=$art->stock-$dato['cantidad'];
            $art->save();
        }
        
    }
    
    public function show($id)
    {
        
    }

    
    public function edit($id)
    {
        $ventas=Venta::find($id);
        return view('venta.edit',compact('ventas'));
    }
    
    public function update(Request $request, $id)
    {
        Articulo::find($id)->update($request->all());
        return redirect()->route('venta.index');        
    }


    public function destroy($id)
    {        
        $dato=Venta::find($id)->delete();        
        return redirect()->route('venta.index');
    }
}

resources/views/articulo/create.blade.php
@extends('layouts.admin')
@section('title', 'Crear Articulo')

@section('sidebar')
    @parent   
    Crear Articulo
@endsection
 
@section('content')
    <div class='jumbotrom'>
        <form method="POST" action="/articulo" >
            @csrf
            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input type="text" name='nombre' class="form-control" placeholder="Nombre">
            </div>                   
            <div class="mb-3">
                <label class="form-label">Color</label>
                <input type="text" name='color' class="form-control" placeholder="Color">
            </div>                   
            <div class="mb-3">
                <label class="form-label">Precio</label>
                <input type="text" name='precio' class="form-control" placeholder="Precio">
            </div>                   
            <div class="mb-3">
                <label class="form-label">Stock</label>
                <input type="text" name='stock' class="form-control" placeholder="Stock">
            </div>                   
            <div class="mb-3">
                <label class="form-label">Descripcion</label>
                <textarea class="form-control" name='descripcion' rows="3"></textarea>            
            </div>                   
            <div class="mb-3">
                <input type="submit" class="btn btn-primary" value="Guardar">
            </div>                   
        </form>
    </div> 
@endsection

resources/views/articulo/edit.blade.php
@extends('layouts.admin')
@section('title', 'Crear Articulo')

@section('sidebar')
    @parent   
    Crear Articulo
@endsection
 
@section('content')
    <div class='jumbotrom'>

        <form method="POST" action="{{ route('articulo.update', $articulo->id) }}">
            <input type="hidden" name="_token" value="{{ csrf_token() }}" />
            <input type="hidden" name="_method" value="PUT" />
                    
            <div class="mb-3">
                <label class="form-label">Nombre</label>                
                <input type="text" name="nombre" class="form-control" value="{{ $articulo->nombre}}"  placeholder="Nombre"/>

            </div>                   
            <div class="mb-3">
                <label class="form-label">Color</label>
                <input type="text" name="color" class="form-control" value="{{ $articulo->color}}"  placeholder="Color"/>                
            </div>                   
            <div class="mb-3">
                <label class="form-label">Precio</label>
                <input type="text" name="precio" class="form-control" value="{{ $articulo->precio}}"  
                placeholder="Precio"/>                                
            </div>                   
            <div class="mb-3">
                <label class="form-label">Stock</label>
                <input type="text" name="stock" class="form-control" value="{{ $articulo->stock}}"  placeholder="Stock"/>                
            </div>                   
            <div class="mb-3">
                <label class="form-label">Descripcion</label>
                
                <textarea class="form-control" rows="3" name="descripcion" value="{{ $articulo->descripcion}}"></textarea>
            </div>                   
            <div class="mb-3">
                <input type="submit" class="btn btn-secondary" value="Actualizar">
            </div>                   
        </form>
        
 
    </div> 
@endsection
    

resources/views/articulo/index.blade.php
@extends('layouts.admin')
@section('title', 'ARTICULO')

@section('sidebar')
    @parent   
    ARTICULOS
@endsection
 
@section('content')
    <div class='jumbotrom'>
        
        
        <a href="/articulo/create" class="btn btn-primary">Crear</a>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Precio</th>
                    <th scope="col">Color</th>
                    <th scope="col">Stock</th>
                    <th scope="col">Descripcion</th>
                    <th scope="col">Opciones</th>
                </tr>
            </thead>
            <tbody>
        @foreach($articulos as $articulo)                                    
            <tr>
                <th scope="row">{{$articulo->id}}</th>
                <td>{{$articulo->nombre}}</td>
                <td>{{$articulo->precio}}</td>
                <td>{{$articulo->color}}</td>
                <td>{{$articulo->stock}}</td>
                <td>{{$articulo->descripcion}}</td>
                <td>
                    
                    <a href="{{ route('articulo.edit', $articulo->id) }} " class="btn btn-primary">Editar</a>                    

                    <form action="/articulo/{{$articulo->id}}" method="post">
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                        @csrf
                    </form>
                    
                
                </td>
            </tr>                
        @endforeach        
            </tbody>
        </table>

        </ul>
    </div> 
@endsection

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <!-- VUE  -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <!-- AXIOS  -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <!-- ROUTE -->
    <script src="https://cdn.jsdelivr.net/npm/vue-router/dist/vue-router.js"></script>
    
    <title>------ @yield('title')</title>

</head>
<body>
    @section('sidebar')
    <nav class="navbar navbar-expand-lg bg-warning">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">------</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/articulo">ARTICULOS</a>
                </li>

                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/venta">VENTAS</a>
                </li>                
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            </div>
        </div>
    </nav>
    @show

    <div class="container">
        @yield('content')
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

resources/views/venta/create.blade.php
@extends('layouts.admin')
@section('title', 'Crear Venta')

@section('sidebar')
    @parent   
    Crear Venta
@endsection
 
@section('content')
    
    <div id="app">

        
        <div class='jumbotrom'>        
            
            <form @submit.prevent="enviar">
                @csrf
                <div class="mb-3">
                    <label class="form-label">Nombre del comprador</label>
                        {{Form::select('user_id',$usuarios , null, ['class' => 'form-control'])}}
                        <div class="row">
                            <div class="col">
                                Producto
                            </div>
                            <div class="col">
                                Cantidad
                            </div>
                            <div class="col">
                                Costo
                            </div>
                            <div class="col">
                                Total
                            </div>
                        </div>    
                        @foreach ($articulos as $i=>$dato)   
                        
                        <div class="row">
                            <div class="col p-1">
                                <button type="button" class="btn btn-secondary position-relative">
                                    {{$dato->nombre}}
                                    <span class="position-absolute top-0 start-100 translate-middle p-2  rounded-circle">
                                        <span class="badge text-bg-dark">{{$dato->stock}}</span>
                                    </span>
                                </button>
                                
                                {{ Form::checkbox('articulos[]',$dato->id,['class'=>'form-control'])}}
                                                                
                            </div>
                            <div class="col">                                
                                <input v-model="articles[{{$i}}].cantidad" 
                                v-on:change="calcularPrecio(articles[{{$i}}],articles[{{$i}}].cantidad,articles[{{$i}}].costo)" 
                                type="number" name="cantidad{{ $dato->id }}">
                            </div>
                            <div class="col">                                                                
                                <input v-model="articles[{{$i}}].costo" 
                                v-on:change="calcularPrecio(articles[{{$i}}],articles[{{$i}}].cantidad,articles[{{$i}}].costo)" 
                                type="text" name="precio{{$dato->id}}">
                            </div>
                            <div class="col">                     
                                <input v-model="articles[{{$i}}].total"
                                type="text" disabled>
                            </div>
                        </div>                                                            
                        @endforeach
                        <div class="row">
                            <h2>                                
                                <div class="col-10 text-end">
                                    total
                                </div>
                            </h2>
                        </div>                                                        
                </div>                   
                
                <div class="mb-3">                                       
                    <input type="submit">
                </div> 

                @{{devolucion}}                
                <br>
                ______________________
                @{{articles}}                  
                ______________________
                <br>
                
            </form>
        </div> 

        
    </div>

<script>
    new Vue({
        el: '#app',
        data: {                     
            articles: [
                @foreach($articulos as $articulo)
                { 
                    id: {{$articulo->id}},
                    nombre: "{{$articulo->nombre}}",
                    stock: {{$articulo->stock}},
                    costo: {{$articulo->precio}},
                    cantidad: 0,                    
                    total:0,
                },
                @endforeach
            ],
            devolucion:[],
        },
        methods: {
            calcularPrecio(i,cant,prec) {
                i.total=cant*prec;
                //this.articles['total']=cant;
            },
            enviar(){                
                
                axios.post('/venta',this.articles)
                .then(response => {                
                    this.devolucion=response.data
                })
                .catch(err => { 
                    // error 
                })
            }
        },
        computed:{
            calcularstock(){
                return 3*3;
            }
        }                        

    });
</script>
@endsection

resources/views/venta/edit.blade.php
@extends('layouts.admin')
@section('title', 'Crear Articulo')

@section('sidebar')
    @parent   
    Crear Articulo
@endsection
 
@section('content')
    <div class='jumbotrom'>

        <form method="POST" action="{{ route('articulo.update', $articulo->id) }}">
            <input type="hidden" name="_token" value="{{ csrf_token() }}" />
            <input type="hidden" name="_method" value="PUT" />
                    
            <div class="mb-3">
                <label class="form-label">Nombre</label>                
                <input type="text" name="nombre" class="form-control" value="{{ $articulo->nombre}}"  placeholder="Nombre"/>

            </div>                   
            <div class="mb-3">
                <label class="form-label">Color</label>
                <input type="text" name="color" class="form-control" value="{{ $articulo->color}}"  placeholder="Color"/>                
            </div>                   
            <div class="mb-3">
                <label class="form-label">Precio</label>
                <input type="text" name="precio" class="form-control" value="{{ $articulo->precio}}"  
                placeholder="Precio"/>                                
            </div>                   
            <div class="mb-3">
                <label class="form-label">Stock</label>
                <input type="text" name="stock" class="form-control" value="{{ $articulo->stock}}"  placeholder="Stock"/>                
            </div>                   
            <div class="mb-3">
                <label class="form-label">Descripcion</label>
                
                <textarea class="form-control" rows="3" name="descripcion" value="{{ $articulo->descripcion}}"></textarea>
            </div>                   
            <div class="mb-3">
                <input type="submit" class="btn btn-secondary" value="Actualizar">
            </div>                   
        </form>
        
 
    </div> 
@endsection
    

resources/views/venta/index.blade.php
@extends('layouts.admin')
@section('title', 'ARTICULO')

@section('sidebar')
    @parent   
    ARTICULOS
@endsection
 
@section('content')
    <div class='jumbotrom'>                
        <a href="/venta/create" class="btn btn-primary">Crear</a>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Total</th>                    
                    <th scope="col">Opciones</th>
                </tr>
            </thead>
            <tbody>
            @foreach($ventas as $dato)                                    
            <tr>
                <th scope="row">{{$dato->id}}</th>
                <td>{{$dato->name}}</td>
                <td>{{$dato->monto_total}}</td>                                
                <td>
                    <a href="{{ route('venta.edit', $dato->id) }} " class="btn btn-primary">Editar</a>
                    <form action="/venta/{{$dato->id}}" method="post">
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                        @csrf
                    </form>

                    <a href="{{ route('pdf1', $dato->id) }}" class="btn btn-warning">PDF Venta</a>
                </td>
            </tr>                
            @endforeach        
            </tbody>
        </table>
        </ul>
    </div> 
@endsection

resources/views/venta/pdf1.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <table style="border:1px solid red;"> 
        <th style="border:1px solid red;">
            <tr>
                <td>id</td>
                <td>nombre</td>
                <td>cantidad</td>
                <td>precio</td>
                <td>total</td>
            </tr>

        </th>
        <tbody style="border:1px solid red;">
            @foreach($detalles as $detalle)
            
                <tr style="border:1px solid red;">
                    <td style="border:1px solid red;">{{$detalle->id}}</td>
                    <td>{{$detalle->nombre}}</td>                    
                </tr>


            @endforeach
            
        </tbody>

    </table>
        
    
    
</body>
</html>